version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: quizzeo
      POSTGRES_PASSWORD: quizzeo
      POSTGRES_DB: quizzeo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgres://quizzeo:quizzeo@db:5432/quizzeo
      JWT_SECRET: votre_super_secret_aleatoire
      BACKEND_PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_PROXY_TARGET=http://backend:3001
    depends_on:
      - backend

volumes:
  db_data:
